### ISSUE TITLE
GET model: how does the generated entity name map to the unique entity in the knowledge graph

### ISSUE THREAD

**Issue by HuuuNan** [facebookresearch/GROOV#2]
Hi there,

Thanks for your interesting work _Entity Tagging: Extracting Entities in Text Without Mention Supervision_.
The GET model seems to generate a sequence of entity names. But how does the entity name generated by the model map the unique entity ID in the knowledge graph if there are multiple entities that have the same entity name. For example, the generated entity name is Forrest Gump, the entity ID100 refers to the movie Forrest Gump, the entity ID101 refers to the character Forrest Gump. Which entity should the generated entity name Forrest Gump map to?

**Comment by acDante** [comment]
Hi HuuuNan,

Thanks for your interest in our work! We created a knowledge base using the entity names in Wikipedia, and each entity is uniquely identified by the title of its corresponding Wikipedia page. In your example, the film Forrest Gump is mapped to 
"Forrest Gump" (Wiki page: https://en.wikipedia.org/wiki/Forrest_Gump), while the character with the same name is mapped to "Forrest Gump (character)" (Wiki page: https://en.wikipedia.org/wiki/Forrest_Gump_(character)). So if the generated entity name is Forrest Gump, it refers to the movie. 

Hope it helps!

**Comment by HuuuNan** [comment]
Thanks.
